### ISSUE TITLE
extra space in SOLR_ULIMIT_CHECKS var in solr.in.sh.j2

### ISSUE THREAD

**Issue by kzila** [idealista/solrcloud-role#106]
### Prerequisites

Install role with ansible-galaxy install -r requirements.txt
$cat requirements.txt
- src: idealista.solrcloud-role
  version: 2.4.0
  name: idealista.solrcloud-role

### Description

There is an extra space in SOLR_ULIMIT_CHECKS var in solr.in.sh.j2

### Steps to Reproduce

1.  grep  SOLR_ULIMIT_CHECKS ./templates/solr.in.sh.j2

**Expected behavior:** 
`SOLR_ULIMIT_CHECKS="{{ solr_ulimit_checks }}"`

**Actual behavior:**
`SOLR_ULIMIT_CHECKS= "{{ solr_ulimit_checks }}"`

**Reproduces how often:** 100%

### Versions

2.4.0

### Additional Information

I can push this small fix if needed, just dont have perms.

**Comment by sorobon** [comment]
Will be resolved in the next release :)

**Comment by kzila** [comment]
Great, thank you so much.
