### ISSUE TITLE
Prometheus exporter installation support

### ISSUE THREAD

**Issue by sorobon** [idealista/solrcloud-role#84]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filled: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aidealista
    * Checked that there is not already provided the described functionality

### Description

Solr now provides a [prometheus exporter](http://lucene.apache.org/solr/guide/7_3/monitoring-solr-with-prometheus-and-grafana.html) to collect the metrics exposed.
Maybe a good idea to include this feature in this role (its similar to collections behaviour).

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

The version/s you notice the behavior.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by jnogol** [comment]
https://lucene.apache.org/solr/guide/7_3/monitoring-solr-with-prometheus-and-grafana.html#starting-the-exporter

**Comment by dortegau** [comment]
It would be nice if prometheus solr exporter role were referenced in this Readme file.
